name: Coverage Report

on: [push]  # You can configure the trigger as needed

jobs:
  coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install coverage package
        run: pip install coverage
        
      - name: Install Poetry and Dependencies
        run: |
          pip install poetry
          poetry install


      - name: Run Tests and Coverage
        run: |
          coverage run -m pytest
          coverage report -m
        #env:
        #  COVERAGE_FILE: ${{ runner.workspace }}/coverage/.coverage  # Set the path to the coverage file

      - name: Publish Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: /coverage
          #path: ${{ runner.workspace }}#/coverage