name: Coverage Report

on: [push]  # You can configure the trigger as needed

jobs:
  coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install coverage package
        run: pip install coverage

      - name: Install Poetry and Dependencies
        run: |
          pip install poetry
          pip install pytest
          poetry install


      - name: Run Tests and Coverage
        run: |
          poetry run coverage -m pytest
          poetry run coverage html
        #env:
        #  COVERAGE_FILE: ${{ runner.workspace }}/coverage/.coverage  # Set the path to the coverage file

      - name: Publish Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          #path: /coverage
          path: ${{ runner.workspace }}

      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v2

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: coverage.svg

      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage.svg
          git commit -m "Updated coverage.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.EZPRIT }}
