name: Run PyTest with Poetry

on: [push] # Define the trigger, e.g., run on every push

jobs:
  test:
    name: Run PyTest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # This step checks out your code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11 # Set the desired Python version

    - name: Install Poetry
      run: |
        pip install poetry
        poetry install

    - name: Run PyTest
      run: |
        poetry run pytest # Run your PyTest suite